### ISSUE TITLE
[TODO] Improve GitHub PR & Bug templates

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#107] opened 2023-02-27 17:34 UTC
While the templates we are using currently, This project is still using the old legacy Markdown templates.

Migrate the templates by both imroving the templates and also changing to GitHubs new .yml Yaml template files.

**Comment by Dylan-Clarry** [comment] 2023-02-27 22:12
I've been wanting to learn how to make these Github PR templates + I know YAML. Can I give this a shot?

**Comment by gbowne1** [comment] 2023-02-27 22:16
Go for it! I would like to make this project as professional and polished as it could get and that we do development in the same manner..  The old workflow was deprecated (but still used) by GitHub ages ago.  I have some links but I would have to unbury them.

While what we have so far is good.. It can be vastly improved.  the main thing is to use the config.yml file in .github

**Comment by Dylan-Clarry** [comment] 2023-02-27 22:24
Sounds good! And if you have any extra links/guidelines for this just send them my way. Otherwise I'll just post updates

**Comment by gbowne1** [comment] 2023-02-27 22:28
I feel like most of what is needed to be referenced is starting here:

https://docs.github.com/en/github-ae@latest/communities/using-templates-to-encourage-useful-issues-and-pull-requests

there's some sub paths on this URL that could be useful.. but start there.

**Comment by Dylan-Clarry** [comment] 2023-02-27 22:29
got it, thanks!

**Comment by Dylan-Clarry** [comment] 2023-03-02 21:40
Hey @gbowne1! Sorry this has taken me a while to get to, this week ended up being super busy out of no where.

I got around to writing some stuff today and this is what it looks like:

![yaml-demo](https://user-images.githubusercontent.com/26127235/222560916-c7297cdc-fcab-4766-85cd-fc98c7a3a170.png)

You can see the full thing in this repo here (create and issue to test it): [https://github.com/Dylan-Clarry/i-will-delete-this-later/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml](url)

Unfortunately I have no more time tonight but if this looks like its headed in the right direction I'll have it finished in the morning.

Thanks

**Comment by gbowne1** [comment] 2023-03-02 21:54
Oh yeah that is superb @Dylan-Clarry ! Thanks.  I won't rush you to get it done.  I'm about quality over quanity.  We  can work on slowly improving it.  GitHub's configuration documentation for this is spotty at best. 

If you are able to get it done right with config.yml you can do this as seen if you click on the Issues tab over there, you can add other issue/bug reporters
 
![Screenshot 2023-03-02 at 13-52-58 New Issue · gbowne1_SPMS_ERP_MRPUpdatedRepo](https://user-images.githubusercontent.com/47549872/222566776-e0f956fd-4d3a-4faf-9f3d-f243aff89a8b.png)

**Comment by gbowne1** [comment] 2023-03-02 22:09
These are the files we used to create the above comment. 

<https://github.com/gbowne1/SPMS_ERP_MRPUpdatedRepo/tree/main/.github/ISSUE_TEMPLATE>

![Screenshot 2023-03-02 at 14-07-18 SPMS_ERP_MRPUpdatedRepo_ github_ISSUE_TEMPLATE at main · gbowne1_SPMS_ERP_MRPUpdatedRepo](https://user-images.githubusercontent.com/47549872/222569700-29be212a-ea9f-4a8a-aa8e-a16f89bf5e75.png)

Docs suggest using a config.yml I mean we could have various things for different reporting to make triage easier.

**Comment by gbowne1** [comment] 2023-03-09 08:17
Any progress on this @Dylan-Clarry ?

**Comment by Dylan-Clarry** [comment] 2023-03-10 01:10
Hey @gbowne1, really sorry I haven't given you an update, I've gotten super busy out of no where. I had some trouble with a couple of things but I can dedicate time to finishing this tomorrow, it is almost done.

**Comment by gbowne1** [comment] 2023-03-10 01:44
No worries at all, just checking in to see if there was any progress. What I saw you had done was really nice

**Comment by Dylan-Clarry** [comment] 2023-03-11 03:13
Hey @gbowne1! I made some more changes to the templates, you can check them out [here](https://github.com/Dylan-Clarry/i-will-delete-this-later/issues/new/choose).

Some notes:
- In Bug Report, I merged the desktop and smartphone section into one and put a "Device" input so they can specify between the two. I felt that having both felt redundant as people can just tell us which device(s) they are using. Let me know how you feel about this and I can always change it back.
- I added a preset label '🐛❔unconfirmed bug' when someone opens a new bug report. I saw this in another [repo](https://github.com/t3-oss/create-t3-app/issues) and it made it easy to distinguish between a brand new bug issue that needs review and one that a maintainer has confirmed is a bug (where they would change the label to 'bug'). If you think this is a good idea then we will need to make an '🐛❔unconfirmed bug' label
- I created a config.yml and added a Slack link. Let me know if any other links belong here

Other than that I just need to test the pr template and we should be all set.

**Comment by gbowne1** [comment] 2023-03-11 04:13
@Dylan-Clarry That sounds good to me.  I had a look and it looks good to me :) :+1: 

The config.yml is the key to this as far as I have been able to see.  GitHub's documents on this are a bit all over the place.
although you can create something like bug_report.yml or some other name.

I like the idea of modifying the default label set which is a whole other task I made an issue for a while back. #112 

I assume that I will eventually create an organization on GitHub for this if we are able to get support for it.  That comes with some better tools but this will do for now.

If you need anything directly you can use the Slack or open a Discussion.  Slack is a fairly commonplace thing these days for decent sized projects.

**Closed** 2023-03-11 19:56 UTC
Labels: documentation, enhancement, help wanted, question
